config/routes.rb
Rails.application.routes.draw do

  get 'profil/vinceprofil'
  get 'profil/myprofile'
  get 'profil/profil'
  get 'carriere' => 'carriere#carriere'
  get 'creation_offre' => 'creation_offre#creation_offre'
  get 'vue_offre' => 'vue_offre#vue_offre'
  get 'evenement' => 'evenement#evenement'
  get 'new_event' => 'new_event#new_event'
  get 'vue_event' => 'vue_event#vue_event'
  get 'messagerie' => 'messagerie#messagerie'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carriere_controller.rb
class CarriereController < ApplicationController
  def carriere
  end
end

app/controllers/creation_offre_controller.rb
class CreationOffreController < ApplicationController
  def creation_offre
  end
end

app/controllers/evenement_controller.rb
class EvenementController < ApplicationController
  def evenement
  end
end

app/controllers/messagerie_controller.rb
class MessagerieController < ApplicationController
  def messagerie
  end
end

app/controllers/myprofile_controller.rb
class MyprofileController < ApplicationController
  def myprofile
  end
end

app/controllers/new_event_controller.rb
class NewEventController < ApplicationController
  def new_event
  end
end

app/controllers/profil_controller.rb
class ProfilController < ApplicationController
  def profil
    @disable_sidebar = true
  end
end

app/controllers/vinceprofil_controller.rb
class VinceprofilController < ApplicationController
  def vinceprofil
  end
end

app/controllers/vue_event_controller.rb
class VueEventController < ApplicationController
  def vue_event
  end
end

app/controllers/vue_offre_controller.rb
class VueOffreController < ApplicationController
  def vue_offre
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


  def index
    @disable_nav = true
    @disable_sidebar = true
    @disable_footer = true
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/myprofile_helper.rb
module MyprofileHelper
end

app/helpers/profil_helper.rb
module ProfilHelper
end

app/helpers/vinceprofil_helper.rb
module VinceprofilHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carriere/carriere.html.erb
<%=  stylesheet_link_tag 'carriere'%>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

<div class="container-carriere">

<div class="panel panel-default">
  <div class="panel-body">

    <h3>Recherche de poste</h3>

    <br>
    <form class="form-inline">
      <div class="form-group inner-addon left-addon">
        <i class="glyphicon glyphicon-briefcase"></i>
        <label class="sr-only" for="poste">Poste</label>
        <input type="text" class="form-control" id="poste" placeholder="Poste, mots clés, entreprise">
      </div>
      <div class="form-group inner-addon left-addon">
        <i class="glyphicon glyphicon-map-marker"></i>
        <label class="sr-only" for="lieux">Lieux</label>
        <input type="text" class="form-control" id="lieux" placeholder="Région, département, ville">
      </div>
      <button type="submit" class="btn btn-default">Trouver un poste</button>
    </form>

    <br>

    <a href="../creation_offre"> <h5 style="color:white;">Déposer une annonce</h5> </a>

  </div>
</div>

  <section>
    <h4>Accédez à vos offres personnalisées maintenant</h4>

  </section>


<!-- Centered Pills -->

<div id="rootwizard">
  <ul class="nav nav-pills nav-justified">
    <li class="active"><a href="#tab1" data-toggle="pill">Découverte</a></li>
    <li><a href="#tab2" data-toggle="pill">Sauvegardées</a></li>
    <li><a href="#tab3" data-toggle="pill">Préférences</a></li>
  </ul>
  <hr>
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">

      <div class="row">
        <div class="col-sm-6 col-md-4 col-lg-3">
          <div class="thumbnail">
            <div class="caption">
              <span class="media-left"><img class="img-circle" src=<%= asset_path 'assystem.png' %>  width="60" height="60"></span>
              <h3 class="media-right media-middle">Assystem France</h3><br>
              <p>Intitulé : Technicien informatique</p>
              <p>Lieux : Vitrolles, 13127</p>
              <p>Type de contrat : CDI</p>
              <p class="detail"><a href="../vue_offre" class="btn btn-info" role="button">Détail</a>
                <a href="#" class="btn btn-info">Sauvegarder</a></p>
              <hr>
              <p class="small">Publiée le 03-12-2016</p>
            </div>
          </div>
        </div>

        <div class="col-sm-6 col-md-4 col-lg-3">
          <div class="thumbnail">
            <div class="caption">
              <span class="media-left"><img class="img-circle" src=<%= asset_path 'blizzard.jpeg' %>  width="60" height="60"></span>
              <h3 class="media-right media-middle">Blizzard</h3><br>
              <p>Intitulé : Designer 3D</p>
              <p>Lieux : Paris, Ile de France</p>
              <p>Type de contrat : CDI</p>
              <p class="detail"><a href="#" class="btn btn-info" role="button">Détail</a>
                <a href="#" class="btn btn-info" role="button">Sauvegarder</a></p>
              <hr>
              <p class="small">Publiée le 05-12-2016</p>
            </div>
          </div>
        </div>

        <div class="col-sm-6 col-md-4 col-lg-3">
          <div class="thumbnail">
            <div class="caption">
              <span class="media-left"><img class="img-circle" src=<%= asset_path 'dassault.png' %>  width="60" height="60"></span>
              <h3 class="media-right media-middle">Dassault Aviation</h3><br>
              <p>Intitulé : Ingénieur sécurité système embarqués</p>
              <p>Lieux : Istres</p>
              <p>Type de contrat : CDI</p>
              <p class="detail"><a href="#" class="btn btn-info" role="button">Détail</a>
                <a href="#" class="btn btn-info" role="button">Sauvegarder</a></p>
              <hr>
              <p class="small">Publiée le 03-12-2016</p>
            </div>
          </div>
        </div>

        <div class="col-sm-6 col-md-4 col-lg-3">
          <div class="thumbnail">
            <div class="caption">
              <span class="media-left"><img class="img-circle" src=<%= asset_path 'bnp.jpeg' %>  width="60" height="60"></span>
              <h3 class="media-right media-middle">BNP Paribas</h3><br>
              <p>Intitulé : Chef de projet data-scientist</p>
              <p>Lieux : Paris, la défense</p>
              <p>Type de contrat : CDI</p>
              <p class="detail"><a href="" class="btn btn-info" role="button">Détail</a>
                <a href="#" class="btn btn-info" role="button">Sauvegarder</a></p>
              <hr>
              <p class="small">Publiée le 03-12-2016</p>
            </div>
          </div>
        </div>
      </div>


    </div>
    <div class="tab-pane" id="tab2">
      <div class="row">
        <div class="col-sm-6 col-md-4 col-lg-3">
          <div class="thumbnail">
            <div class="caption">
              <span class="media-left"><img class="img-circle" src=<%= asset_path 'assystem.png' %>  width="60" height="60"></span>
              <h3 class="media-right media-middle">Assystem France</h3><br>
              <p>Intitulé : Technicien informatique</p>
              <p>Lieux : Vitrolles, 13127</p>
              <p>Type de contrat : CDI</p>
              <p class="detail"><a href="#" class="btn btn-info" >Détail</a>
                <a href="#" class="btn btn-info" >Supprimer</a></p>
              <hr>
              <p class="small">Publiée le 03-12-2016</p>
            </div>
          </div>
        </div>

        <div class="col-sm-6 col-md-4 col-lg-3">
          <div class="thumbnail">
            <div class="caption">
              <span class="media-left"><img class="img-circle" src=<%= asset_path 'blizzard.jpeg' %>  width="60" height="60"></span>
              <h3 class="media-right media-middle">Blizzard</h3><br>
              <p>Intitulé : Designer 3D</p>
              <p>Lieux : Paris, Ile de France</p>
              <p>Type de contrat : CDI</p>
              <p class="detail"><a href="#" class="btn btn-info" >Détail</a>
                <a href="#" class="btn btn-info">Supprimer</a></p>
              <hr>
              <p class="small">Publiée le 05-12-2016</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-pane" id="tab3">
      <div class="body-pref">

        <header class="panelpanel-default">
          <div class="panel-body jumbotron">

            <h3>Aidez nous à trouver votre futur job !</h3>

          </div>
        </header>


        <div class="container">
          <form>
            <fieldset>
              <div class="form-group ">
                <label for="formGroupExampleInput">Indiquez nous votre mobilité : </label>
                <input data-role="tagsinput" value="" type="text" class="form-control" id="formGroupExampleInput" placeholder="Région, département, ville">
              </div>
              <div class="form-group">
                <label for="formGroupExampleInput2">Quel(s) domaine(s) vous intéresse ?</label>
                <input data-role="tagsinput" type="text" class="form-control" id="formGroupExampleInput2" placeholder="Jeux vidéos, développement web">
              </div>

              <div class="form-group">
                <label for="formGroupExampleInput2">Vous êtes interessé par :</label>
                <input data-role="tagsinput" type="text" class="form-control" id="formGroupExampleInput2" placeholder="Renseignez les technolgies sur lesquelles vous souhaitez travailler">
              </div>

              <div class="form-group">
                <label>Quelle expérience avez vous pour le(s) poste(s) recherché(s) :</label><br>
                <label class="custom-control custom-radio">
                  <input id="radio1" name="radio" type="radio" class="custom-control-input">
                  <span class="custom-control-indicator"></span>
                  <span class="custom-control-description">Stagiaire</span>
                </label>
                <label class="custom-control custom-radio">
                  <input id="radio2" name="radio" type="radio" class="custom-control-input">
                  <span class="custom-control-indicator"></span>
                  <span class="custom-control-description">Jeune diplômé</span>
                </label>
                <label class="custom-control custom-radio">
                  <input id="radio1" name="radio" type="radio" class="custom-control-input">
                  <span class="custom-control-indicator"></span>
                  <span class="custom-control-description">Junior</span>
                </label>
                <label class="custom-control custom-radio">
                  <input id="radio1" name="radio" type="radio" class="custom-control-input">
                  <span class="custom-control-indicator"></span>
                  <span class="custom-control-description">Expert</span>
                </label>
                <label class="custom-control custom-radio">
                  <input id="radio1" name="radio" type="radio" class="custom-control-input">
                  <span class="custom-control-indicator"></span>
                  <span class="custom-control-description">Manager</span>
                </label>
                <label class="custom-control custom-radio">
                  <input id="radio1" name="radio" type="radio" class="custom-control-input">
                  <span class="custom-control-indicator"></span>
                  <span class="custom-control-description">Directeur</span>
                </label>

              </div>

              <button type="button" class="btn btn-default btn-primary">Enregistrer</button>
            </fieldset>
          </form>
        </div>




      </div>


      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </div>


  </div>
</div>
</div>

app/views/profil/myprofile.html.erb
<%= stylesheet_link_tag 'myprofile' %>

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

<style>
  body{
    padding-top:90px;
    background-color: #e3ebee;
  }

  .media-right{
    float:right;
  }
  .btn-outline-info{
    border: 1px solid deepskyblue;
  }

  .panel {
    box-shadow: 0 2px 0 rgba(0,0,0,0.075);
    border-radius: 0;
    border: 0;
    margin-bottom: 15px;
  }

    .date{
      font-size:12px;
      color:lightslategrey;;
    }

</style>
<body>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container bootstrap snippets">
<div class="col-md-3">
  <div class="panel rounded shadow">
    <div class="panel-body">
      <div class="inner-all">
        <ul class="list-unstyled">
          <li class="text-center">
            <%= image_tag "profilepic2",:class=>"img-circular"%>
          </li>
          <li class="text-center">
            <h4 class="text-capitalize"><%= link_to 'John Doe', profil_myprofile_path %></h4>
            <p class="text-muted text-capitalize">Developpeur Web</p>
            <a href="http://www.github.com"><i class="fa fa-github fa-2x" aria-hidden="true"></i></a>
          </li>
          <li>
          </li>
          <li><br></li>
          <li>
            <div class="btn-group-vertical btn-block">
              <a href="" class="btn btn-default"><i class="fa fa-cog pull-right"></i>Paramètres du compte</a>
              <a href="../" class="btn btn-default"><i class="fa fa-sign-out pull-right"></i>Se Déconnecter</a>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

  <div class="col-md-6">
  <div class="panel panel-default">
   <div class="panel-body"> <div class = "btn-group" style="float:right"><a class="btn btn-outline-secondary dropdown-toggle" data-toggle = "dropdown" href="#" role="button"><i class="fa fa-cog" aria-hidden="true"></i></a>
     <ul class = "dropdown-menu" role = "menu">
       <li><a href = "#" style="size:10px">Modifier</a></li>
     </ul>
   </div>
    <h4><i class="fa fa-file-text" aria-hidden="true"></i> Résumé</h4>
       <p style="font-size:95%">Bonjour !
         Développeur pro-actif, je suis sans cesse à la recherche de projets à réussir.
         N'hésitez pas à consulter mon compte Github pour avoir un aperçu de mes travaux personnels.
         Dernier projet réalisé: un système de messagerie instantanée multimédia complet pour le web, intégré à une plateforme Java EE.
       </p>
     <div class = "btn-group" style="float:right"><a class="btn btn-outline-secondary dropdown-toggle" data-toggle = "dropdown" href="#" role="button"><i class="fa fa-cog" aria-hidden="true"></i></a>
       <ul class = "dropdown-menu" role = "menu">
         <li><a href = "#" style="size:10px">Modifier</a></li>
       </ul>
     </div>
     <hr>
     <h4><i class="fa fa-file-code-o" aria-hidden="true"></i> Expérience</h4>
        <p>
            <span class="media-right"><img src=<%= asset_path 'assystem.png' %>  width="70" height="60"></span>
            <strong>Developpeur Java</strong><br>
            <a href="#" >Assystem</a><br>
            <span class="date">Mars 2014 - Aujourd'hui (2 ans 9 mois)</span>
            <p style="font-size:95%">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.
              Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor.
              Cras elementum ultrices diam.</p>
        </p>
      <br>
     <br>
     <p>
       <span class="media-right"><img src=<%= asset_path 'bnp.jpeg'%>  width="90" height="50"></span>
       <strong>Developpeur Java</strong><br>
       <a href="#">BNP Paribas</a><br>
       <span class="date">Juin 2013 - Mars 2014 (9 mois)</span>
     <p style="font-size:95%">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.
       Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor.
       Cras elementum ultrices diam.</p>
     </p>
     <br>
     <br>
     <p>
       <span class="media-right"><img class="img-circle" src=<%= asset_path 'web.jpeg' %>  width="60" height="60"></span>
       <strong>Developpeur Web</strong><br>
       <a href="#">Webprod</a><br>
       <span class="date"> Décembre 2012 - Juin 2013 (6 mois)</span>
     <p style="font-size:95%">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.
       Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor.
       Cras elementum ultrices diam.</p>
     </p><div class = "btn-group" style="float:right"><a class="btn btn-outline-secondary dropdown-toggle" data-toggle = "dropdown" href="#" role="button"><i class="fa fa-cog" aria-hidden="true"></i></a>
     <ul class = "dropdown-menu" role = "menu">
       <li><a href = "#" style="size:10px">Modifier</a></li>
     </ul>
   </div>
     <hr>

     <h4><i class="fa fa-code" aria-hidden="true"></i> Compétences</h4>
     <p>HTML 5
       <progress class="progress" value="75" max="100"></progress></p>
     <p>
     <p>CSS 3
       <progress class="progress" value="70" max="100"></progress>
     <p>
     <p>Javascript
       <progress class="progress" value="75" max="100"></progress>
     <p>
     <p>Java
       <progress class="progress" value="100" max="100"></progress></p>
     <p>
     </p>
     <div class = "btn-group" style="float:right"><a class="btn btn-outline-secondary dropdown-toggle" data-toggle = "dropdown" href="#" role="button"><i class="fa fa-cog" aria-hidden="true"></i></a>
       <ul class = "dropdown-menu" role = "menu">
         <li><a href = "#" style="size:10px">Modifier</a></li>
       </ul>
     </div>
     <hr>

     <h4><i class="fa fa-star" aria-hidden="true"></i> Centres d'intérêts</h4>
     <p>
       <button type="button" class="btn btn-outline-info" disabled>UX Design</button>
       <button type="button" class="btn btn-outline-info" disabled>Cinéma</button>
       <button type="button" class="btn btn-outline-info" disabled>Photographie</button>
     </p>

     <hr>

     <h4><i class="fa fa-star" aria-hidden="true"></i> Ajouter un CV</h4>
     <label class="custom-file">
       <input type="file" id="file" class="custom-file-input">
       <span class="custom-file-control"></span>
     </label>
     <p>

     </p>

      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="panel rounded shadow">
      <div class="panel-body">
       <strong><p style="text-align:center">Qui a consulté votre profil ?</p></strong>
        <br>

        <p><%= link_to profil_vinceprofil_path do %>
              <%= image_tag "profilpic3",:class=>"img-circular2"%>
          <% end %></p><div style="color: deepskyblue;">Vince Mach</div>
        UX Designer
        <br>
        <br>


        <p><a href="#"><%= image_tag "profilepic2",:class=>"img-circular2"%></a></p><div style="color: deepskyblue;">Steve Jobs</div>
        Developpeur Swift
        <br>
        <br>


        <p><a href="#"><%= image_tag "profilepic4",:class=>"img-circular2"%></a></p><div style="color: deepskyblue;">Lisa J.</div>
        Developpeuse .Net
        <br>
        <br>

        <p><a href="#"><%= image_tag "profilpic3",:class=>"img-circular2"%></a></p><div style="color: deepskyblue;">Michael Sachs</div>
        WebDesigner
        <br>
      </div>
    </div>
  </div>

</div>
</body>

app/views/profil/vinceprofil.html.erb
<%= stylesheet_link_tag 'myprofile' %>

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

<style>
  body{
    padding-top:90px;
    background-color: #e3ebee;
  }
  .media-right{
    float:right;
  }

  .btn-outline-info{
    border: 1px solid deepskyblue;
    margin-bottom: 10px;

  }

  .bouton{
    text-align: center;
  }

  .panel {
    box-shadow: 0 2px 0 rgba(0,0,0,0.075);
    border-radius: 0;
    border: 0;
    margin-bottom: 15px;
  }

  .date{
    font-size:12px;
    color:lightslategrey;;
  }

  .btn-outline-info{
    border: 1px solid deepskyblue;
  }

  .btn-outline-info:hover{
    color:white;
    background-color:deepskyblue;
  }

</style>
<body>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container bootstrap snippets">
  <div class="col-md-3">
    <div class="panel rounded shadow">
      <div class="panel-body">
        <div class="inner-all">
          <ul class="list-unstyled">
            <li class="text-center">
              <%= image_tag "profilpic3",:class=>"img-circular"%>
            </li>
            <li class="text-center">
              <h4 class="text-capitalize"><%= link_to 'Vince Mach', profil_vinceprofil_path %></h4>
              <p class="text-muted text-capitalize">UX Designer</p>
              <a href="http://www.github.com"><i class="fa fa-github fa-2x" aria-hidden="true"></i></a>
            </li>
            <li>
            </li>
            <li><br></li>
          </ul>
               <div class="bouton" >
                <a href="#" class="btn btn-outline-info">Se Connecter</a>
                <a href="#" class="btn btn-outline-info">Envoyer un message</a>
               </div>

        </div>
      </div>
    </div>
  </div>

  <div class="col-md-6">

    <div class="panel panel-default">
      <div class="panel-body">
        <h4><i class="fa fa-file-text" aria-hidden="true"></i> Résumé</h4>
        <p style="font-size:95%">Passionné de jeux-vidéos et de design depuis mon plus jeune âge, je suis actuellement employé
          par Blizzard, en tant que Game Designer. Je travaille sur un nouveau projet de jeu dont la sortie est prévu en 2018.
        </p>
        <hr>
        <h4><i class="fa fa-file-code-o" aria-hidden="true"></i> Expérience</h4>
        <p>
          <span class="media-right"><img class="img-circle" src=<%= asset_path 'blizzard.jpeg' %>  width="60" height="60"></span>
          <strong>UX Designer</strong><br>
          <a href="#">Blizzard</a><br>
          <span class="date">Mars 2014 - Aujourd'hui (2 ans 9 mois)</span>
        <p style="font-size:95%">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.
          Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor.
          Cras elementum ultrices diam.</p>
        </p>
        <br>
        <br>
        <p>
          <span class="media-right"><img src=<%= asset_path 'dassault.png' %>  width="90" height="60"></span>
          <strong>Designer</strong><br>
          <a href="#">Dassault</a><br>
          <span class="date">Juin 2013 - Mars 2014 (9 mois)</span>
        <p style="font-size:95%">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus.
          Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor.
          Cras elementum ultrices diam.</p>
        </p>
        <br>
        <br>

        <hr>

        <h4><i class="fa fa-code" aria-hidden="true"></i> Compétences</h4>
        <p>HTML 5
          <progress class="progress" value="75" max="100"></progress></p>
        <p>
        <p>CSS 3
          <progress class="progress" value="70" max="100"></progress>
        <p>
        <p>Javascript
          <progress class="progress" value="75" max="100"></progress>
        <p>
        <p>Java
          <progress class="progress" value="100" max="100"></progress></p>
        <p>
        </p>

        <hr>

        <h4><i class="fa fa-star" aria-hidden="true"></i> Centres d'intérêts</h4>
        <p>
          <button type="button" class="btn btn-outline-info" disabled>UX Design</button>
          <button type="button" class="btn btn-outline-info" disabled>Cinéma</button>
          <button type="button" class="btn btn-outline-info" disabled>Photographie</button>
        </p>

      </div>
    </div>
  </div>

  <div class="col-md-3">
    <div class="panel rounded shadow">
      <div class="panel-body">
        <p style="text-align: center">Qui a consulté votre profil ?</p>
        <br>

        <p><a href="#"><%= image_tag "profilepic2",:class=>"img-circular2"%></a></p><div style="color: deepskyblue;">Steve Jobs</div>
        Developpeur Swift
        <br>
        <br>


        <p><a href="#"><%= image_tag "profilepic4",:class=>"img-circular2"%></a></p><div style="color: deepskyblue;">Lisa J.</div>
        Developpeuse .Net
        <br>
        <br>

        <p><a href="#"><%= image_tag "profilpic3",:class=>"img-circular2"%></a></p><div style="color: deepskyblue;">Michael Sachs</div>
        WebDesigner
        <br>


      </div>
    </div>
  </div>

</div>
</body>

app/views/shared/_footer.html.erb
 <div style="text-align: center">
     <h3>CodersNet</h3>
     Copyright 2016. All Rights Reserved by CodersNet.com
  </div>
</div>

app/views/welcome/index.html.erb
        <%= stylesheet_link_tag 'welcome' %>
        <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet'  type='text/css'>
         <body>

            <div class="wrapper">
            <div class="login is-active">
              <br>
              <br>
              <h1><i class="fa fa-code" aria-hidden="true"></i>  &#60/&#62 CodersNet</h1>
              <br>
              <br>
              <br>
              <br>
              <div class="form-element">
                <span><i class="fa fa-envelope"></i></span><input type="email" placeholder="Adresse Email"/>
              </div>
              <div class="form-element">
                <span><i class="fa fa-lock"></i></span><input type="password" placeholder="Mot de Passe"/>
              </div>
              <button class="btn-login"><%= link_to 'Login', profil_profil_path %></button>
            </div>
            <div class="register down">
              <div class="form-element">
                <span><i class="fa fa-user"></i></span><input type="text" placeholder="Prénom"/>
              </div>
              <div class="form-element">
                <span><i class="fa fa-user"></i></span><input type="text" placeholder="Nom"/>
              </div>
              <div class="form-element">
                <span><i class="fa fa-envelope"></i></span><input type="email" placeholder="Adresse Email"/>
              </div>
              <div class="form-element">
                <span><i class="fa fa-lock"></i></span><input type="password" placeholder="Mot de Passe"/>
              </div>
              <div class="form-element">
                <span><i class="fa fa-lock"></i></span><input type="password" placeholder="Confirmez le mot de passe"/>
              </div>
              <button class="btn-register">S'inscrire</button>
            </div>
            <div class="login-view-toggle">
              <div class="sign-up-toggle is-active">Pas encore de compte ? <a href="#">Inscrivez-vous!</a></div>
              <div class="login-toggle">Déjà inscrit ? <a href="#">Login</a></div>
            </div>
          </div>
         </body>